{{- if .Values.job.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chekr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chekr.labels" . | nindent 4 }}
data:
  chekr.yaml: |
{{ toYaml .Values.job.config | indent 4 }}
{{- end }}
