{{- if .Values.job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chekr.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chekr.labels" . | nindent 4 }}
  {{- with .Values.job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
