pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=lint-test
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
      
  - name: say hi on new contribution
    conditions: []
    actions:
        comment:
          message: |
              Thanks for your pull request!
              The owner of this repository will try to review and merge this as soon as possible.

  - name: ask to resolve conflict
    conditions:
      - conflicts
    actions:
        comment:
          message: This pull request has now conflicts with the base branch. Could you please try to fix them? 🙏
