{{- if .Values.podSecurityPolicy.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cadvisor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadvisor.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cadvisor.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "cadvisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
