apiVersion: v1
kind: Service
metadata:
  name: {{ template "cadvisor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadvisor.labels" . | nindent 4}}
spec:
  ports:
  - name: http
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    {{- include "cadvisor.selectorLabels" . | nindent 4 }}
  type: ClusterIP
