apiVersion: v1
kind: Service
metadata:
  name: {{ template "cadvisor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cadvisor.name" . }}
    chart: {{ template "cadvisor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    app: {{ template "cadvisor.name" . }}
  type: {{ .Values.service.type }}
