{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cadvisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadvisor.labels" . | nindent 4 }}
{{- end -}}
