{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- end -}}
