apiVersion: v1
description: Prometheus Blackbox Exporter
name: prometheus-blackbox-exporter
version: 1.0.0
appVersion: 0.16.0
home: https://github.com/prometheus/blackbox_exporter
sources:
  - https://github.com/prometheus/blackbox_exporter
  - https://github.com/code-chris/helm-charts
keywords:
  - prometheus
  - blackbox
  - monitoring
maintainers:
  - name: code-chris
    email: christian.kotzbauer@gmail.com
