apiVersion: v1
description: Prometheus Blackbox Exporter
name: prometheus-blackbox-exporter
version: 1.0.3
appVersion: 0.18.0
home: https://github.com/prometheus/blackbox_exporter
sources:
  - https://github.com/prometheus/blackbox_exporter
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - prometheus
  - blackbox
  - monitoring
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
