name: Label Issues
on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.3.4"
      - name: label
        uses: "ckotzbauer/label-command-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
