name: stale
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-stale.yml@9e2a560f6c957fe29a2a78f8cbadabeea56a8c73 # 0.52.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
